### ISSUE TITLE
Web Application

### ISSUE THREAD

**Issue by emilytaylor97** [Aden-Training/Training_Portal#11]
As a user, I want to be able to access the website easily, so that there is an order to the website making it easy to navigate.

**Comment by AlexanderRacey** [comment]
I have researched a method to include a link from the client's Wix website to the newly created application. We will include a large, highlighted button onto the original site that will take the user straight to the login page of the application. The method on how to do this can be found here: https://support.wix.com/en/article/adding-a-link-to-an-image
