### ISSUE TITLE
Website tidying up

### ISSUE THREAD

**Issue by amelia-handley** [Aden-Training/Training_Portal#2]
As a user, I want to be able to view a well designed website that has a good user interface, to make the website easy to navigate.

**Comment by AlexanderRacey** [comment]
I have included a responsive side navigational menu for course categories, allowing users to view different group types of courses on the page.

**Comment by AlexanderRacey** [comment]
I have updated the appearance of the _customerHome_ page displaying customer details and their obtained certificates.

**Comment by rossbelldev** [comment]
Fixed spelling errors on his page, all changes and fixes on our page are being sorted by alex
