### ISSUE TITLE
Access to Certificates

### ISSUE THREAD

**Issue by emilytaylor97** [Aden-Training/Training_Portal#3]
As a user, I want to be able to view my employees training profiles, so that I can view employee certificates and can prove that my colleagues have received their training.

**Comment by amelia-handley** [comment]
Need to add the certificates to the profile pages.

**Comment by Tyler1551** [comment]
User can see certificates, although it downloads a corrupted file

**Comment by Tyler1551** [comment]
Certificates viewable from profile pages and load in browser
