### ISSUE TITLE
Website Organisation

### ISSUE THREAD

**Issue by amelia-handley** [Aden-Training/Training_Portal#4]
As an administrator, I want my website to look professional throughout with easy navigation, so that my users are able to access what they need easily whilst using my website.

**Comment by amelia-handley** [comment]
Alex has created wireframes of the basic design and has been working on some of the design for the web application.

**Comment by AlexanderRacey** [comment]
I have created a navigational menu system that is responsive to when the application window is resized, giving users the ability to move to any page featured onto the website with simplicity.

**Comment by AlexanderRacey** [comment]
I have implemented a responsive website header section that adapts its display depending on the size of the application window, this includes a desktop display and a mobile display.

**Comment by rossbelldev** [comment]
Closing as all appearance side of things have been made to look professional and easy to navigate by alex
