### ISSUE TITLE
Company profiles

### ISSUE THREAD

**Issue by emilytaylor97** [Aden-Training/Training_Portal#8]
As a user, I want to be able to access my employee training, so that I can view all my colleagues training information.

**Comment by Tyler1551** [comment]
Logging in for customer and business not working due to password encoding with bcrypt

**Comment by Tyler1551** [comment]
Issue resolved, user can now see their certificates on their profile page

**Comment by amelia-handley** [comment]
Certificates added to profiles. Needs additional HTML formatting.

**Comment by Tyler1551** [comment]
Companies can now view, add or remove employees from the database

**Comment by rossbelldev** [comment]
All of the above issues have been addressed and resolved/implemented. Closing issue
